library(ggplot2)
library(hrbrthemes)
library(dplyr)
library(tidyr)
library(viridis)

data2 <- read.delim("gisaid_hcov-clinical.csv", header = TRUE, sep = ',')

data2$Patient_status <- as.factor(data2$Patient_status)
data2$Patient_age <- as.numeric(data2$Patient_age)
data2$Patient_status[data2$Patient_status == "Alive"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Deceased"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "live"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Live"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Live "] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Death"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "Released"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Recovered"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Home"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Cured"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "hospitalized"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Released, Live"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Quarantine"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Quarantined"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Recovering"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Discharged"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized/Released"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized, deceased"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "Discharged after recovery"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == " Released"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized, released"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == " Released"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "Pneumonia (chest X-ray)"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Recovered and Released"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized; Stable"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Mild clinical signs without hospitalization"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized/Deceased"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized, deceased"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "In-hospital"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Intensive Care Unit"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "Isolation"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Not Hospitalized"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "inpatient"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "outpatient"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Symptomatic"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Hopsitalized"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized (Intensive care unit)"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "Symptoms indicative of upper respiratory infection"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Initially hospitalized, but now improved and discharged"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Stable in quarantine"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Mild symptoms (fever, cardiovascular disorders)"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "hospitalized or to be hospitalized"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized or to be hospitalized"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "EHPAD"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Physician network"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Screening"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Mild symptoms inpatient for observation"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Mild/Contact exposure/Asymptomatic"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Moderate/Outpatient"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Severe/ICU"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "Mild"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Hospitaized"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Mild, at home."] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Live, mild symptoms, at home"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Still hospitalized"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Outpatient"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Asymptomatic, identified as positive during preoperation investigation"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized, oxygenotherapy, diarrhea"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "ICU"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "Asymptomatic/Released"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Not hospitalized"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "EHPAD_IRA"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Released "] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized "] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "symptomatic"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "DAMA"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Hospsitalized, ICU, fully recovered"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalized in ICU"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "Hospitalised"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "ICD-10 Disease: J06.9 Acute upper respiratory infection, unspecified"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "ICD-10 Disease: Z03.8 Observation for other suspected diseases and conditions"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Bronchitis"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Epidemiology Study"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Oro-pharyngeal swab"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "ICU; Serious"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "ICD-10 Disease: Z20.8 Contact with and exposure to other communicable diseases"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "ICD-10 CODE: J20.9 â€“ ACUTE BRONCHITIS, UNSPECIFIED"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "ICD-10 Disease:J18.9 Pneumonia, unspecified organism"] <- "Mild Reaction"
data2$Patient_status[data2$Patient_status == "Severe / ICU"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "Mild / Contact exposure / Asymptomatic"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "deceased"] <- "Worst Reaction"
data2$Patient_status[data2$Patient_status == "asymptomatic"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Moderate / Outpatient"] <- "Best Reaction"
data2$Patient_status[data2$Patient_status == "Physician"] <- "Mild Reaction"

age <- data2$Patient_age

status <- data2$Patient_status

ggplot(data = data2, aes(x=age, group=status, fill=status)) + geom_density(adjust=1.5, position = "fill") + theme_ipsum() + ggtitle("Age Distribution of Immunity Reaction")

write.csv(data2, "gisaid_hcov-clinical-filt-dolu.csv")
